TODO fix watermark generation
Signed-off-by: Jonas Dujava <jonas.dujava@gmail.com>

diff --git a/figures/Inkscape/inkscape-export-to-latex b/figures/Inkscape/inkscape-export-to-latex
--- a/figures/Inkscape/inkscape-export-to-latex
+++ b/figures/Inkscape/inkscape-export-to-latex
@@ -1,25 +1,28 @@
 #!/bin/sh
 
-[ -z "$1" ] && echo "Usage: $0 <figure name>" && exit 1
-[ ! -f "$1.svg" ] && echo "File $1.svg not found" && exit 1
-
-## Export Inkscape SVG to PDF+LaTeX code
-inkscape "$1.svg" --export-area-drawing --export-dpi=300 --export-latex --export-filename="$1.pdf"
-
-## Disable interpolation in the PDF (to conform with PDF/A standard)
-# sed -i 's|/Interpolate true$|/Interpolate false|' "$1.pdf" # sometimes CORRUPTS the PDF
-## https://stackoverflow.com/questions/20011515/how-to-remove-anti-aliasing-in-pdf-images
-perl -M-encoding -0777pe "s|/Interpolate true|' 'x17|ge" <"$1.pdf" >"$1-fixed.pdf"
+# [ -z "$1" ] && echo "Usage: $0 <figure name>" && exit 1
+# [ ! -f "$1.svg" ] && echo "File $1.svg not found" && exit 1
+#
+# ## Export Inkscape SVG to PDF+LaTeX code
+# inkscape "$1.svg" --export-area-drawing --export-dpi=300 --export-latex --export-filename="$1.pdf"
+#
+# ## Disable interpolation in the PDF (to conform with PDF/A standard)
+# # sed -i 's|/Interpolate true$|/Interpolate false|' "$1.pdf" # sometimes CORRUPTS the PDF
+# ## https://stackoverflow.com/questions/20011515/how-to-remove-anti-aliasing-in-pdf-images
+# perl -M-encoding -0777pe "s|/Interpolate true|' 'x17|ge" <"$1.pdf" >"$1-fixed.pdf"
 
 ## Add watermark to the PDF (if watermark script is available)
 directory=$(dirname "$1")
 if [ -f "$directory/add-watermark" ]; then
     ## try to extract the author's name from the LaTeX preamble
-    author_name=$(sed -n 's/^[^%].*ThesisAuthorPlaintext}{}{\(.*\)}$/\1/p' preamble/data.tex)
+    author_name=$(sed -nE 's/^[^%].*authorplaintext.*=.*\{(.*)\},?$/\1/p' thesis.tex)
     ## if the `\ThesisAuthorPlaintext` command is commented out, extract from the `\ThesisAuthor` command
-    [ -z "$author_name" ] && author_name=$(sed -n 's/.*ThesisAuthor}{}{\(.*\)}$/\1/p' preamble/data.tex)
+    [ -z "$author_name" ] && author_name=$(sed -nE 's/^[^%].*author.*=.*\{(.*)\},?$/\1/p' thesis.tex)
     ## use just ASCII characters, see https://unix.stackexchange.com/a/653210
     author_name=$(echo "$author_name" | uconv -x Latin-ASCII)
+    echo "Author's name: $author_name"
+
+    exit 0
 
     watermark_string="$(date +%Y) $author_name"  # prepend the year
     # watermark_string="$(date +%Y) Author's Name" # NOTE: or manually edit the watermark string here
